## To modify Stefano's input into 1 required table (including iLUC)

from MR_HUSE.csv and iLUC.xlsx

## 1. Steps to build the Ready-for-CSV terminated file automatically:
1. Extract first 4 columns from "naming.xlsx", tab "terminated-xl"
2. Extract first 7 rows from "naming.xlsx", tab "terminated-xl"
3. Round BLCI numbers
4. Remove zeros from BLCI_rounded
5. Concatenate frame1, frame2, BLCI_rounded_without_zeros
6. Export to excel "terminated-v3310b2.xlsx"

In [2]:
cd /Users/marie/Desktop

/Users/marie/Desktop


In [189]:
import pandas as pd
BLCI_rounded = pd.read_csv("BLCI_rounded.csv", header = None)
F2_rounded = pd.read_csv("F2_rounded.csv", header = None)

In [195]:
terminated_values = pd.concat([BLCI_rounded, F2_rounded], axis = 1)
terminated_values = terminated_values.reset_index(drop = True)
terminated_values.columns = [i for i in range(terminated_values.shape[1])]
terminated_values.columns.values

array([   0,    1,    2, ..., 8157, 8158, 8159])

In [194]:
import pandas as pd
import csv
data_xls = pd.read_excel('naming.xlsx', 'terminated-xl', index_col=None, header = None, encoding='utf-8')
column_headings = data_xls.iloc[0:7, 4:8165]
column_headings = column_headings.reset_index(drop = True)
column_headings.columns = [i for i in range(column_headings.shape[1])]
column_headings.columns.values

array([   0,    1,    2, ..., 8157, 8158, 8159])

In [197]:
column_headings.index.values

array([0, 1, 2, 3, 4, 5, 6])

In [196]:
terminated = pd.concat([column_headings, terminated_values])
outfile ="/Users/marie/Desktop/column_headings.csv"
terminated.to_csv(outfile, header = False, index = False)

In [202]:
terminated = terminated.reset_index(drop = True)
terminated.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143])

In [204]:
row_headings = data_xls.iloc[0:144, 0:4]
row_headings.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143])

In [206]:
ready_for_csv = pd.concat([row_headings, terminated], axis = 1)
outfile ="/Users/marie/Desktop/ready_for_csv.csv"
ready_for_csv.to_csv(outfile, header = False, index = False)

In [ ]:
__logBase10of2 = 3.010299956639811952137388947244930267681898814621085413104274611e-1
import numpy as np

def RoundToSigFigs( x, sigfigs ):
    """
    Rounds the value(s) in x to the number of significant figures in sigfigs.
    Restrictions:
    sigfigs must be an integer type and store a positive value.
    x must be a real value or an array like object containing only real values.
    """
    if not ( type(sigfigs) is int or np.issubdtype(sigfigs, np.integer)):
        raise TypeError( "RoundToSigFigs: sigfigs must be an integer." )
    if not np.all(np.isreal( x )):
        raise TypeError( "RoundToSigFigs: all x must be real." )
    if sigfigs <= 0:
        raise ValueError( "RoundtoSigFigs: sigfigs must be positive." )
    mantissas, binaryExponents = np.frexp( x )
    decimalExponents = __logBase10of2 * binaryExponents
    intParts = np.floor(decimalExponents)
    mantissas *= 10.0**(decimalExponents - intParts)
    return np.around( mantissas, decimals=sigfigs - 1 ) * 10.0**intParts

In [ ]:
BLCI_rounded = RoundToSigFigs(BLCI,7)

In [24]:
BLCI_rounded = pd.DataFrame(BLCI_rounded)
F2_rounded = pd.DataFrame(F2_rounded)

In [5]:
BLCI_rounded_without0 = BLCI_rounded.replace(0, r'\s+', regex=True)
F2_rounded_without0 = F2_rounded.replace(0, r'\s+', regex=True)

In [ ]:
ready_for_csv.to_excel('terminated_v3310b2.xlsx', encoding='utf-8', index=False, header=False)

## 2. Steps to build the Ready-for-csv linked files automatically
1. Extract first 4 columns from naming.xlsx, tab "linked-excel"
2. Extract activity names and following 6 rows from naming.xlsx "linked-excel" from country1 to country6
3. Round Zn, Bn numbers
4. Remove zeros from Zn, Bn
5. Concatenate frame1, frame2-X, Zn, Bn
6. Export to excel
"linked_v3310b1_AU-AT-BE-BR-BG-CA"  
"linked_v3310b1_CN-CY-CZ-DK-EE-FI"  
"linked_v3310b1_FR-DE-GR-HU-HR-IN"  
"linked_v3310b1_ID_IE_IT_JP_LV_LT"  
"linked_v3310b1_LU-MT-MX-NL-NO-PL"  
"linked_v3310b1_PT-RO-RU-SK-SI-ZA"  
"linked_v3310b1_yKR-ES-SE-CH-TR-GB"  
"linked_v3310b1_zUS-WA-WL-WE-WF-WM"  

Steps to build the Ready-for-csv market files automatically  
"product_markets_v3310"  
"electricity_markets_v3310"  
"iLUC_markets_v3310"  

Read "MR_HUSE.csv" as source1 and extract Zn, Bn, norm, Use, BnUse.

In [2]:
import pandas as pd
import csv

source1 = pd.read_csv('MR_HUSE.csv', index_col = None, header = None, low_memory = False)

In [3]:
Zn = source1.iloc[7:2959, 5:2957]
Use = source1.iloc[7:2959, 2958:3066]

Bn_raw = source1.iloc[2960:2994, 5:2957]
Bn_occupation = source1.iloc[2995:3085, 5:2957]
Bn_emissions = source1.iloc[3086:3147, 5:2957]

frame1 = [Bn_raw, Bn_occupation, Bn_emissions]
Bn = pd.concat(frame1)

BnUse_raw = source1.iloc[2960:2994, 2958:3066]
BnUse_occupation = source1.iloc[2995:3085, 2958:3066]
BnUse_emissions = source1.iloc[3086:3147, 2958:3066]

frame2 = [Bn_raw, Bn_occupation, Bn_emissions]
BnUse = pd.concat(frame2)

Create iLUC1 empty frame to account for additional corresponding columns for activities.

In [4]:
import numpy as np

iLUC = np.empty(shape=(2952,17))
np.savetxt("iLUC.csv", iLUC, delimiter=",")

iLUC1 = pd.read_csv("iLUC.csv", index_col = None, header=None, low_memory = False)

In [12]:
outfile1 ="/Users/marie/Desktop/Zn_iLUC_USE_pd.csv"

frame3 = [Zn, iLUC1, Use]
Zn_iLUC_USE = pd.concat(frame3, axis=1)

Zn_iLUC_USE.to_csv(outfile1, header = None)

Read iLUC.xlsx as source2 to extract iLUC2 et iLUC3.

In [13]:
import pandas as pd

source2 = pd.read_excel('iLUC.xlsx', sheetname = 'ZBfa', index_col = None, header = None, convert_float = True)
iLUC2 = source2.iloc[7:29, 4:3081]

outfile2 ="/Users/marie/Desktop/iLUC2_pd.csv"
iLUC2.to_csv(outfile2, header = None)

In [7]:
iLUC3 = source2.iloc[29:214, 2956:2973]

In [14]:
outfile3 ="/Users/marie/Desktop/Bn_iLUC3_BnUse_pd.csv"

frame4 = [Bn, iLUC3, BnUse]
Bn_iLUC3_BnUse = pd.concat(frame4, axis=1)

Bn_iLUC3_BnUse.to_csv(outfile3, header = None)

Concatenate the remaining frames frame3, iLUC3 and frame4 to form the masterfile content.

In [11]:
import csv

outfile = "/Users/marie/Desktop/masterfile.csv"

frame5 = [Zn_iLUC_USE, iLUC2, Bn_iLUC3_BnUse]
masterfile = pd.concat(frame5)

masterfile.to_csv(outfile, header = None)

TypeError: concat() got an unexpected keyword argument 'index_col'

Add norm vector

In [ ]:
norm1 = source1.iloc[1:2, 5:2957]
norm2 = source2.iloc[2:3, 2956:3081]